spring.application.name=backend
spring.graphql.cors.allowed-origins=*
spring.graphql.path=/graphql
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/wirc}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
wirc.state-file=${WIRC_STATE_FILE:./data/chat-state.json}
